### ISSUE TITLE
Plot symbols like high symmetry points

### ISSUE THREAD

**Issue by zybbigpy** [thchr/Brillouin.jl#10]
<img width="538" alt="WeChat0cf57af31c9a39548070baef1c833207" src="https://user-images.githubusercontent.com/24970890/129024296-c575c239-5eb8-416c-91e5-e7ec80ff521d.png">
Hello, I am a beginner in Julia. I want to know when I use the `Plot` Api, how can I get the high symmetry symbols on the plot just like the logo?

**Comment by thchr** [comment]
You unfortunately cannot get an exact replica of this plot in Brillouin - but you can get something quite close to it as [described in the documentation](https://thchr.github.io/Brillouin.jl/stable/kpaths/). With the Plotly plot, you can hover over each high-symmetry **k**-point to see the label.
Assigning staticly visible labels to 3D plots without having lots of "overlapping" artifacts always struck me as tricky; I don't know if it's possible in Plotly, unfortunately.

**Comment by thchr** [comment]
Seems it can be done reasonably nicely in Plotly after all (https://plotly.com/javascript/text-and-annotations/#3d-annotations) although the syntax is sort of painful. 
I might add this at some point, but may take a while to find time.

**Comment by thchr** [comment]
You can do this via Makie now:
```jl
using Brillouin, GLMakie
using Bravais # for `directbasis`

n = 39
kp = irrfbz_path(n, directbasis(n, 3))
c = wignerseitz(basis(kp))
f, ax, p = plot(c)
plot!(ax, kp)
f
```
Which will produce a plot like this one: 
<img width="267" alt="image" src="https://user-images.githubusercontent.com/26799210/187575997-36b34492-9a0a-4272-a49a-b038d4c24237.png">

**Comment by zybbigpy** [comment]
So Cool!
