### ISSUE TITLE
latticize!(kp::KPath{D}, Gs::BasisLike{D}) not implemented

### ISSUE THREAD

**Issue by jaemolihm** [thchr/Brillouin.jl#12]
Hi,
the docstring mentions `latticize!(kp::KPath{D}, Gs::BasisLike{D})`, but the corresponding function was deleted in f32a826b6205009184c886c98fc914a2db6c9382.

If I understood correctly, `latticize!(kp, Gs)` allows one to convert the Cartesian k path to reduced coordinates using any reciprocal basis `Gs`, not just using the default `kp.basis`. This functionality is very useful, so I hope the function is implemented again.

**Comment by thchr** [comment]
Ah, good catch. Before restoring it, I wanted to understand your use-case better: is it e.g. to convert a path from one initial lattice basis to another? I.e., would the use of `latticize!(kp, Gs)` always come in this combination `latticize!(cartesianize!(kp), newGs)`?

**Comment by jaemolihm** [comment]
Yes, my use case is exactly what you said.
