### ISSUE TITLE
Using Brillouin assumes scipy is installed if system python is used

### ISSUE THREAD

**Issue by mfherbst** [thchr/Brillouin.jl#17]
Currently the `__init__` code in https://github.com/thchr/Brillouin.jl/blob/53e1e804d0411f0c4b474525de7f0b10fc010adc/src/WignerSeitz.jl#L35 assumes the user is either using Julia's internal conda environment or that the user has scipy installed. If this is not the case (e.g. if one uses the distribution-managed system python) `Brillouin` fails.

From skimming the code I noted that `PySpatial` is only used inside the `wignerseitz` function, which is not used a lot inside `Brillouin`. Would it be ok to move the python import into that function (i.e. remove it from module scope) and make it optional such that only this function fails in case scipy is not installed? What I have in mind, is a pattern like
```
PySpatial = pyimport_e("scipy.spatial")
if ispynull(PySpatial)
   PyCall.conda || error("Install scipy")
   PySpatial = pyimport_conda("scipy.spatial", "scipy")
end
```
That way, for Conda.jl users everything is still automatic, otherwise you get an error, but only if the function is actually needed. Would that be ok with you @thchr ?

**Comment by mfherbst** [comment]
Good point about the `__init__`, but the solution is simple. You put my snipped inside the init and you only error when someone actually calls `wignerseitz`. I'm happy to code up a patch. We can also issue a warning in the `__init__` if you want.

**Comment by thchr** [comment]
That'd be very welcome! Thanks!
